/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MoonService } from "../moon.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MoonCreateInput } from "./MoonCreateInput";
import { Moon } from "./Moon";
import { MoonFindManyArgs } from "./MoonFindManyArgs";
import { MoonWhereUniqueInput } from "./MoonWhereUniqueInput";
import { MoonUpdateInput } from "./MoonUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MoonControllerBase {
  constructor(
    protected readonly service: MoonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Moon })
  @nestAccessControl.UseRoles({
    resource: "Moon",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MoonCreateInput,
  })
  async createMoon(@common.Body() data: MoonCreateInput): Promise<Moon> {
    return await this.service.createMoon({
      data: data,
      select: {
        color: true,
        createdAt: true,
        id: true,
        name: true,
        period: true,
        secondStart: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Moon] })
  @ApiNestedQuery(MoonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Moon",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async moons(@common.Req() request: Request): Promise<Moon[]> {
    const args = plainToClass(MoonFindManyArgs, request.query);
    return this.service.moons({
      ...args,
      select: {
        color: true,
        createdAt: true,
        id: true,
        name: true,
        period: true,
        secondStart: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Moon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Moon",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async moon(
    @common.Param() params: MoonWhereUniqueInput
  ): Promise<Moon | null> {
    const result = await this.service.moon({
      where: params,
      select: {
        color: true,
        createdAt: true,
        id: true,
        name: true,
        period: true,
        secondStart: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Moon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Moon",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MoonUpdateInput,
  })
  async updateMoon(
    @common.Param() params: MoonWhereUniqueInput,
    @common.Body() data: MoonUpdateInput
  ): Promise<Moon | null> {
    try {
      return await this.service.updateMoon({
        where: params,
        data: data,
        select: {
          color: true,
          createdAt: true,
          id: true,
          name: true,
          period: true,
          secondStart: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Moon })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Moon",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMoon(
    @common.Param() params: MoonWhereUniqueInput
  ): Promise<Moon | null> {
    try {
      return await this.service.deleteMoon({
        where: params,
        select: {
          color: true,
          createdAt: true,
          id: true,
          name: true,
          period: true,
          secondStart: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
