/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TimeService } from "../time.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TimeCreateInput } from "./TimeCreateInput";
import { Time } from "./Time";
import { TimeFindManyArgs } from "./TimeFindManyArgs";
import { TimeWhereUniqueInput } from "./TimeWhereUniqueInput";
import { TimeUpdateInput } from "./TimeUpdateInput";
import { SeasonFindManyArgs } from "../../season/base/SeasonFindManyArgs";
import { Season } from "../../season/base/Season";
import { SeasonWhereUniqueInput } from "../../season/base/SeasonWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TimeControllerBase {
  constructor(
    protected readonly service: TimeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Time })
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TimeCreateInput,
  })
  async createTime(@common.Body() data: TimeCreateInput): Promise<Time> {
    return await this.service.createTime({
      data: data,
      select: {
        createdAt: true,
        id: true,
        isPaused: true,
        seconds: true,
        secondsPerSecond: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Time] })
  @ApiNestedQuery(TimeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async times(@common.Req() request: Request): Promise<Time[]> {
    const args = plainToClass(TimeFindManyArgs, request.query);
    return this.service.times({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isPaused: true,
        seconds: true,
        secondsPerSecond: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Time })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async time(
    @common.Param() params: TimeWhereUniqueInput
  ): Promise<Time | null> {
    const result = await this.service.time({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isPaused: true,
        seconds: true,
        secondsPerSecond: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Time })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TimeUpdateInput,
  })
  async updateTime(
    @common.Param() params: TimeWhereUniqueInput,
    @common.Body() data: TimeUpdateInput
  ): Promise<Time | null> {
    try {
      return await this.service.updateTime({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          isPaused: true,
          seconds: true,
          secondsPerSecond: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Time })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTime(
    @common.Param() params: TimeWhereUniqueInput
  ): Promise<Time | null> {
    try {
      return await this.service.deleteTime({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isPaused: true,
          seconds: true,
          secondsPerSecond: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/seasons")
  @ApiNestedQuery(SeasonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Season",
    action: "read",
    possession: "any",
  })
  async findSeasons(
    @common.Req() request: Request,
    @common.Param() params: TimeWhereUniqueInput
  ): Promise<Season[]> {
    const query = plainToClass(SeasonFindManyArgs, request.query);
    const results = await this.service.findSeasons(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        time: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/seasons")
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "update",
    possession: "any",
  })
  async connectSeasons(
    @common.Param() params: TimeWhereUniqueInput,
    @common.Body() body: SeasonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seasons: {
        connect: body,
      },
    };
    await this.service.updateTime({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/seasons")
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "update",
    possession: "any",
  })
  async updateSeasons(
    @common.Param() params: TimeWhereUniqueInput,
    @common.Body() body: SeasonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seasons: {
        set: body,
      },
    };
    await this.service.updateTime({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/seasons")
  @nestAccessControl.UseRoles({
    resource: "Time",
    action: "update",
    possession: "any",
  })
  async disconnectSeasons(
    @common.Param() params: TimeWhereUniqueInput,
    @common.Body() body: SeasonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seasons: {
        disconnect: body,
      },
    };
    await this.service.updateTime({
      where: params,
      data,
      select: { id: true },
    });
  }
}
