/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TrackerService } from "../tracker.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TrackerCreateInput } from "./TrackerCreateInput";
import { Tracker } from "./Tracker";
import { TrackerFindManyArgs } from "./TrackerFindManyArgs";
import { TrackerWhereUniqueInput } from "./TrackerWhereUniqueInput";
import { TrackerUpdateInput } from "./TrackerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TrackerControllerBase {
  constructor(
    protected readonly service: TrackerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Tracker })
  @nestAccessControl.UseRoles({
    resource: "Tracker",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TrackerCreateInput,
  })
  async createTracker(
    @common.Body() data: TrackerCreateInput
  ): Promise<Tracker> {
    return await this.service.createTracker({
      data: {
        ...data,

        character: data.character
          ? {
              connect: data.character,
            }
          : undefined,
      },
      select: {
        character: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        numberField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Tracker] })
  @ApiNestedQuery(TrackerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Tracker",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trackers(@common.Req() request: Request): Promise<Tracker[]> {
    const args = plainToClass(TrackerFindManyArgs, request.query);
    return this.service.trackers({
      ...args,
      select: {
        character: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        numberField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Tracker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Tracker",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tracker(
    @common.Param() params: TrackerWhereUniqueInput
  ): Promise<Tracker | null> {
    const result = await this.service.tracker({
      where: params,
      select: {
        character: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        numberField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Tracker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Tracker",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TrackerUpdateInput,
  })
  async updateTracker(
    @common.Param() params: TrackerWhereUniqueInput,
    @common.Body() data: TrackerUpdateInput
  ): Promise<Tracker | null> {
    try {
      return await this.service.updateTracker({
        where: params,
        data: {
          ...data,

          character: data.character
            ? {
                connect: data.character,
              }
            : undefined,
        },
        select: {
          character: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          numberField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Tracker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Tracker",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTracker(
    @common.Param() params: TrackerWhereUniqueInput
  ): Promise<Tracker | null> {
    try {
      return await this.service.deleteTracker({
        where: params,
        select: {
          character: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          numberField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
