/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CharacterListRelationFilter } from "../../character/base/CharacterListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ItemBonusWhereUniqueInput } from "../../itemBonus/base/ItemBonusWhereUniqueInput";

@InputType()
class ItemWhereInput {
  @ApiProperty({
    required: false,
    type: () => CharacterListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CharacterListRelationFilter)
  @IsOptional()
  @Field(() => CharacterListRelationFilter, {
    nullable: true,
  })
  character?: CharacterListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  image?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isPublic?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ItemBonusWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ItemBonusWhereUniqueInput)
  @IsOptional()
  @Field(() => ItemBonusWhereUniqueInput, {
    nullable: true,
  })
  itemBonuses?: ItemBonusWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;
}

export { ItemWhereInput as ItemWhereInput };
