/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { ItemUpdateManyWithoutCharactersInput } from "./ItemUpdateManyWithoutCharactersInput";
import { Type } from "class-transformer";
import { EnumCharacterStatuses } from "./EnumCharacterStatuses";
import { TrackerUpdateManyWithoutCharactersInput } from "./TrackerUpdateManyWithoutCharactersInput";
import { TraitSetUpdateManyWithoutCharactersInput } from "./TraitSetUpdateManyWithoutCharactersInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class CharacterUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: () => ItemUpdateManyWithoutCharactersInput,
  })
  @ValidateNested()
  @Type(() => ItemUpdateManyWithoutCharactersInput)
  @IsOptional()
  @Field(() => ItemUpdateManyWithoutCharactersInput, {
    nullable: true,
  })
  items?: ItemUpdateManyWithoutCharactersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCharacterStatuses,
  })
  @IsEnum(EnumCharacterStatuses)
  @IsOptional()
  @Field(() => EnumCharacterStatuses, {
    nullable: true,
  })
  statuses?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => TrackerUpdateManyWithoutCharactersInput,
  })
  @ValidateNested()
  @Type(() => TrackerUpdateManyWithoutCharactersInput)
  @IsOptional()
  @Field(() => TrackerUpdateManyWithoutCharactersInput, {
    nullable: true,
  })
  trackers?: TrackerUpdateManyWithoutCharactersInput;

  @ApiProperty({
    required: false,
    type: () => TraitSetUpdateManyWithoutCharactersInput,
  })
  @ValidateNested()
  @Type(() => TraitSetUpdateManyWithoutCharactersInput)
  @IsOptional()
  @Field(() => TraitSetUpdateManyWithoutCharactersInput, {
    nullable: true,
  })
  traitSets?: TraitSetUpdateManyWithoutCharactersInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { CharacterUpdateInput as CharacterUpdateInput };
